### ISSUE TITLE
`repl` page pdf text selection problem

### ISSUE THREAD

**Issue by Rafat97** [diegomura/react-pdf-site#92]
![image](https://user-images.githubusercontent.com/21246862/195566941-fc1dd625-84dc-4cbf-8b08-d9d281b1f84c.png)

Chrome Version : Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by diegomura** [comment]
This is how pdfjs handles text. Because pages are rendered using a canvas, the engine renders a hidden text element on top to make text selectable. Unfortunately the browser shows it on selection, but this issue it's not related to this lib and there's no much we can do on our end. Closing it unless someone proves me wrong :)
